language: android
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./gradlew build jacocoTestReport