language: android
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov    #Install codecov

after_success:
  - codecov                       #Run codecov
  - .buildscript/deploy_snapshot.sh

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

script: ./gradlew build